{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import gensim\n",
    "from gensim import corpora\n",
    "import pickle\n",
    "import re\n",
    "from spacy.lang.en.stop_words import STOP_WORDS\n",
    "from collections import Counter\n",
    "from nltk.corpus import wordnet\n",
    "import nltk\n",
    "from nltk.tokenize import word_tokenize \n",
    "from nltk.stem import WordNetLemmatizer \n",
    "# import dask.dataframe as dd\n",
    "# from dask.multiprocessing import get\n",
    "import swifter\n",
    "from tqdm import tqdm\n",
    "\n",
    "tqdm.pandas()\n",
    "lemmatizer = WordNetLemmatizer() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "wordnet_map = {\"N\":wordnet.NOUN, \"V\":wordnet.VERB, \"J\":wordnet.ADJ, \"R\":wordnet.ADV}\n",
    "def lemmatize_words(text):\n",
    "    pos_tagged_text = nltk.pos_tag(text.split())\n",
    "    return \" \".join([lemmatizer.lemmatize(word, wordnet_map.get(pos[0], wordnet.NOUN)) for word, pos in pos_tagged_text])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "url_pattern = re.compile(r'https?://\\S+|www\\.\\S+')\n",
    "alpha_pattern = re.compile(r'[^A-Za-z ]+')\n",
    "def clean_up(x):\n",
    "    x = url_pattern.sub(r'', x)\n",
    "    x = alpha_pattern.sub(r'', x)\n",
    "    word_tokens = word_tokenize(x.lower())\n",
    "    filtered_sentence =[]\n",
    "    for w in word_tokens:\n",
    "        if len(w)<3 or w in STOP_WORDS:\n",
    "            continue\n",
    "        filtered_sentence.append(w.lower())\n",
    "    x = []\n",
    "    for word in filtered_sentence:\n",
    "        x.append(lemmatize_words(word))\n",
    "#         x.append(ps.stem(word))\n",
    "    x = \" \".join(x)\n",
    "#     x = lemmatize_words(x)\n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv(\"data/drug_review/drugsComTrain_raw.tsv\",delimiter=\"\\t\")[:11000]\n",
    "test = pd.read_csv(\"data/drug_review/drugsComTest_raw.tsv\",delimiter=\"\\t\")[:4000]\n",
    "break_point = df.shape[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 192, in apply\n",
      "    tmp_df = func(sample, *args, **kwds)\n",
      "  File \"<ipython-input-6-d48a5051b876>\", line 1, in <lambda>\n",
      "    df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))\n",
      "  File \"<ipython-input-4-c866fd77829b>\", line 4, in clean_up\n",
      "    x = url_pattern.sub(r'', x)\n",
      "TypeError: expected string or bytes-like object\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-d48a5051b876>\", line 1, in <module>\n",
      "    df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 212, in apply\n",
      "    return self._dask_apply(func, convert_dtype, *args, **kwds)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 144, in _dask_apply\n",
      "    .compute(scheduler=self._scheduler)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\base.py\", line 175, in compute\n",
      "    (result,) = compute(self, traverse=False, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\base.py\", line 446, in compute\n",
      "    results = schedule(dsk, keys, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\multiprocessing.py\", line 207, in get\n",
      "    **kwargs\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\local.py\", line 476, in get_async\n",
      "    fire_task()\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\local.py\", line 465, in fire_task\n",
      "    dumps((dsk[key], data)),\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\multiprocessing.py\", line 26, in _dumps\n",
      "    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 1108, in dumps\n",
      "    cp.dump(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 473, in dump\n",
      "    return Pickler.dump(self, obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 437, in dump\n",
      "    self.save(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 549, in save\n",
      "    self.save_reduce(obj=obj, *rv)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 638, in save_reduce\n",
      "    save(args)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 786, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 887, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 786, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 816, in save_list\n",
      "    self._batch_appends(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 840, in _batch_appends\n",
      "    save(x)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 816, in save_list\n",
      "    self._batch_appends(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 840, in _batch_appends\n",
      "    save(x)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 887, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 549, in save\n",
      "    self.save_reduce(obj=obj, *rv)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 662, in save_reduce\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 815, in save_list\n",
      "    self.memoize(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 460, in memoize\n",
      "    self.write(self.put(idx))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 464, in put\n",
      "    def put(self, idx):\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2039, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 192, in apply\n",
      "    tmp_df = func(sample, *args, **kwds)\n",
      "  File \"<ipython-input-6-d48a5051b876>\", line 1, in <lambda>\n",
      "    df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))\n",
      "  File \"<ipython-input-4-c866fd77829b>\", line 4, in clean_up\n",
      "    x = url_pattern.sub(r'', x)\n",
      "TypeError: expected string or bytes-like object\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-d48a5051b876>\", line 1, in <module>\n",
      "    df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 212, in apply\n",
      "    return self._dask_apply(func, convert_dtype, *args, **kwds)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 144, in _dask_apply\n",
      "    .compute(scheduler=self._scheduler)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\base.py\", line 175, in compute\n",
      "    (result,) = compute(self, traverse=False, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\base.py\", line 446, in compute\n",
      "    results = schedule(dsk, keys, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\multiprocessing.py\", line 207, in get\n",
      "    **kwargs\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\local.py\", line 476, in get_async\n",
      "    fire_task()\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\local.py\", line 465, in fire_task\n",
      "    dumps((dsk[key], data)),\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\multiprocessing.py\", line 26, in _dumps\n",
      "    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 1108, in dumps\n",
      "    cp.dump(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 473, in dump\n",
      "    return Pickler.dump(self, obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 437, in dump\n",
      "    self.save(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 549, in save\n",
      "    self.save_reduce(obj=obj, *rv)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 638, in save_reduce\n",
      "    save(args)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 786, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 887, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 786, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 816, in save_list\n",
      "    self._batch_appends(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 840, in _batch_appends\n",
      "    save(x)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 816, in save_list\n",
      "    self._batch_appends(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 840, in _batch_appends\n",
      "    save(x)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 887, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 549, in save\n",
      "    self.save_reduce(obj=obj, *rv)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 662, in save_reduce\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 815, in save_list\n",
      "    self.memoize(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 460, in memoize\n",
      "    self.write(self.put(idx))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 464, in put\n",
      "    def put(self, idx):\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2039, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3248, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3342, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2042, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1385, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1288, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in structured_traceback\n",
      "    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)\n",
      "TypeError: can only concatenate str (not \"list\") to str\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2039, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 192, in apply\n",
      "    tmp_df = func(sample, *args, **kwds)\n",
      "  File \"<ipython-input-6-d48a5051b876>\", line 1, in <lambda>\n",
      "    df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))\n",
      "  File \"<ipython-input-4-c866fd77829b>\", line 4, in clean_up\n",
      "    x = url_pattern.sub(r'', x)\n",
      "TypeError: expected string or bytes-like object\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3325, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-6-d48a5051b876>\", line 1, in <module>\n",
      "    df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 212, in apply\n",
      "    return self._dask_apply(func, convert_dtype, *args, **kwds)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\swifter\\swifter.py\", line 144, in _dask_apply\n",
      "    .compute(scheduler=self._scheduler)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\base.py\", line 175, in compute\n",
      "    (result,) = compute(self, traverse=False, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\base.py\", line 446, in compute\n",
      "    results = schedule(dsk, keys, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\multiprocessing.py\", line 207, in get\n",
      "    **kwargs\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\local.py\", line 476, in get_async\n",
      "    fire_task()\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\local.py\", line 465, in fire_task\n",
      "    dumps((dsk[key], data)),\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\dask\\multiprocessing.py\", line 26, in _dumps\n",
      "    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 1108, in dumps\n",
      "    cp.dump(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 473, in dump\n",
      "    return Pickler.dump(self, obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 437, in dump\n",
      "    self.save(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 549, in save\n",
      "    self.save_reduce(obj=obj, *rv)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 638, in save_reduce\n",
      "    save(args)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 786, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 887, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 786, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 771, in save_tuple\n",
      "    save(element)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 816, in save_list\n",
      "    self._batch_appends(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 840, in _batch_appends\n",
      "    save(x)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 816, in save_list\n",
      "    self._batch_appends(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 840, in _batch_appends\n",
      "    save(x)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 887, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 547, in save_function\n",
      "    return self.save_function_tuple(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\cloudpickle\\cloudpickle.py\", line 747, in save_function_tuple\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 549, in save\n",
      "    self.save_reduce(obj=obj, *rv)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 662, in save_reduce\n",
      "    save(state)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 856, in save_dict\n",
      "    self._batch_setitems(obj.items())\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 882, in _batch_setitems\n",
      "    save(v)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 504, in save\n",
      "    f(self, obj) # Call unbound method with explicit self\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 815, in save_list\n",
      "    self.memoize(obj)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 460, in memoize\n",
      "    self.write(self.put(idx))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\pickle.py\", line 464, in put\n",
      "    def put(self, idx):\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2039, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3248, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3342, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2042, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1385, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1288, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in structured_traceback\n",
      "    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)\n",
      "TypeError: can only concatenate str (not \"list\") to str\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2039, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 319, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 353, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"C:\\Users\\am21907\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "can only concatenate str (not \"list\") to str",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2038\u001b[0m                         \u001b[1;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2039\u001b[1;33m                         \u001b[0mstb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2040\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'KeyboardInterrupt' object has no attribute '_render_traceback_'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mrun_code\u001b[1;34m(self, code_obj, result, async_)\u001b[0m\n\u001b[0;32m   3340\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0mresult\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3341\u001b[0m                 \u001b[0mresult\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror_in_exec\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msys\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 3342\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mshowtraceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrunning_compiled_code\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3343\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3344\u001b[0m             \u001b[0moutflag\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[1;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[0;32m   2040\u001b[0m                     \u001b[1;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2041\u001b[0m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[1;32m-> 2042\u001b[1;33m                                             value, tb, tb_offset=tb_offset)\n\u001b[0m\u001b[0;32m   2043\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2044\u001b[0m                     \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_showtraceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mstb\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1383\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1384\u001b[0m         return FormattedTB.structured_traceback(\n\u001b[1;32m-> 1385\u001b[1;33m             self, etype, value, tb, tb_offset, number_of_lines_of_context)\n\u001b[0m\u001b[0;32m   1386\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1387\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1286\u001b[0m             \u001b[1;31m# Verbose modes need a full traceback\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1287\u001b[0m             return VerboseTB.structured_traceback(\n\u001b[1;32m-> 1288\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1289\u001b[0m             )\n\u001b[0;32m   1290\u001b[0m         \u001b[1;32melif\u001b[0m \u001b[0mmode\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m'Minimal'\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\AppData\\Local\\Continuum\\anaconda3\\envs\\ATSC\\lib\\site-packages\\IPython\\core\\ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[1;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[0;32m   1148\u001b[0m         \u001b[0mexception\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_parts_of_chained_exception\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1149\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mexception\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1150\u001b[1;33m             \u001b[0mformatted_exceptions\u001b[0m \u001b[1;33m+=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mprepare_chained_exception_message\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__cause__\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1151\u001b[0m             \u001b[0metype\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mevalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0metb\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mexception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1152\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: can only concatenate str (not \"list\") to str"
     ]
    }
   ],
   "source": [
    "df.review = df.review.swifter.allow_dask_on_strings().apply((lambda row: clean_up(row)))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "test.review = test.review.swifter.allow_dask_on_strings().apply(lambda row: clean_up(row))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "reviews = pd.concat([df.review,test.review])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import Counter\n",
    "cnt = Counter()\n",
    "for text in tqdm(reviews.values):\n",
    "    old_words = []\n",
    "    for word in text.split():\n",
    "        if word not in old_words:\n",
    "            cnt[word] += 1\n",
    "            old_words.append(word)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def remove_rare_freq_words(x):\n",
    "    word_tokens = word_tokenize(x)\n",
    "    x = []\n",
    "    for w in word_tokens:\n",
    "#         print(\"_*_\"*100)\n",
    "        if cnt[w] < high_pruner:\n",
    "            x.append(w)\n",
    "        elif cnt[w] > 20:\n",
    "            x.append[w]\n",
    "    x = \" \".join(x)\n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "high_pruner = reviews.shape[0]*0.65\n",
    "reviews = reviews.progress_apply(lambda x : remove_rare_freq_words(x))\n",
    "reviews[15]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "clean_up(\"I happy had birthday too soon when where ok damn sorry after\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#1. Dict\n",
    "#2. Doc -> tokens token2id ##also remove duplicates\n",
    "#3. Doc -> token_count "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "texts = [[text for text in review.split()] for review in reviews]\n",
    "dictionary = corpora.Dictionary(texts)\n",
    "print(dictionary)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df.review = reviews[:break_point]\n",
    "test.review = reviews[break_point:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def prepare_df(df,col=\"review\"):\n",
    "    df = pd.DataFrame(reviews,columns=[col])\n",
    "    df[\"bow\"] = df[col].apply(lambda x : dictionary.doc2bow(x.split(),))\n",
    "    df[\"tokens\"] = df.bow.apply(lambda x: np.array([[i[0] for i in x]]))\n",
    "    df[\"counts\"] = df.bow.apply(lambda x: np.array([[i[1] for i in x]]))\n",
    "    df.drop(['bow','review'],axis=1,inplace=True)\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = prepare_df(df)\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "train , valid = df.iloc[:int(df.shape[0]*0.9),:],df.iloc[int(df.shape[0]*0.9):,:]\n",
    "print(train.shape)\n",
    "print(valid.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "test = prepare_df(test)\n",
    "print(test.shape)\n",
    "test.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "test , test_1,test_2 = test.iloc[:int(test.shape[0]*0.5),:],test.iloc[int(test.shape[0]*0.5):int(test.shape[0]*0.75),:],test.iloc[int(test.shape[0]*0.75):,:]\n",
    "print(test.shape)\n",
    "print(test_1.shape)\n",
    "print(test_2.shape)\n",
    "# test_1_tokens = test['tokens_1']\n",
    "# test_1_counts = test['counts_1']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "reviews.to_csv(\"data/drug_review/preprocessed_reviews.csv\",index=None,header=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv(\"data/drug_review/preprocessed_reviews.csv\",header=None)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "train"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Saving The Files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "path = \"data/drug_review/\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# train.to_csv(path+\"train.csv\",index=None)\n",
    "# test.to_csv(path+\"test.csv\",index=None)\n",
    "# valid.to_csv(path+\"valid.csv\",index=None)\n",
    "dictionary.save(path+\"vocab.pkl\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def store_bow_files(df,filename):\n",
    "    tokens = df.tokens.tolist()\n",
    "    counts = df.counts.tolist()\n",
    "    dict_ = {\"tokens\":tokens,\"counts\":counts}\n",
    "    with open(path+filename+'.pkl', 'wb') as handle:\n",
    "        pickle.dump(dict_, handle)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "store_bow_files(train,\"train_dict\")\n",
    "store_bow_files(test,\"test_dict\")\n",
    "store_bow_files(test_1,\"test_1_dict\")\n",
    "store_bow_files(test_2,\"test_2_dict\")\n",
    "store_bow_files(valid,\"valid_dict\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Validating The stored Files"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(path + 'train_dict.pkl', 'rb') as handle:\n",
    "    train = pickle.load(handle)\n",
    "train"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(path + 'test_dict.pkl', 'rb') as handle:\n",
    "    test = pickle.load(handle)\n",
    "test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(path + 'valid_dict.pkl', 'rb') as handle:\n",
    "    valid = pickle.load(handle)\n",
    "valid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (AZ Social Media Analytics)",
   "language": "python",
   "name": "atsc"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
